### ISSUE TITLE
공지사항 삭제 이슈

### ISSUE THREAD

**Issue by jeongHunE** [KNUTICE/KNUTICE-SERVER#79]
## 공지가 삭제되어 개수가 점점 줄어드는 이슈

테스트 서버에서 각 카테고리 별 공지사항이 삭제 되어 개수가 점점 줄어드는 이슈가 있습니다.

**Comment by ITSTIME1** [comment]
문제가 발생된 부분을 확인 했고, 삭제 로직 변경 전에 발생했던 문제로 파악되었습니다. 현재 삭제 로직이 변경된 시점이기 때문에 삭제는 정상적으로 작동하고, 이전에 삭제 되어버린 게시글은 복구작업으로 정상화 시도하겠습니다 감사합니다
